input_dir: "/c/Users/tthaker/Downloads/Wakefern_dataset/probes/white_male/109"
output_dir: 'wakefern_masked_new' ##

image_dim: 112
########################################################################################################
# arguments for appending Mask  (NO CHANGE NEEDED) (IGNORE THIS)
########################################################################################################
# Type of the mask to be applied
mask_type: 'surgical'  # Available options: surgical, N95, KN95, cloth, gas, inpaint, random, all

# Type of the pattern
pattern: "random"  # Available options in masks/textures

# Weight of the pattern. Must be between 0 and 1
pattern_weight: 0.5

# Hex color value that needs to be overlayed to the mask
color: "#0473e2"

# Weight of the color intensity. Must be between 0 and 1
color_weight: 0.5

# Generate specific formats
code: ""  # Example format: cloth-masks/textures/check/check_4.jpg, cloth-#e54294, cloth-#ff0000, cloth, cloth-masks/textures/others/heart_1.png, cloth-masks/textures/fruits/pineapple.png, N95, surgical_blue, surgical_green

# Turn verbosity on
verbose: false

# If true, original image is also stored in the masked folder
write_original_image: false

# Offset to be given in order to move mask up or down (Negative for moving up and positive for moving down)
mask_y_offset : 20

# rotation angle
mask_rotation_angle: 0

mask_success :

output_path :

# model: "/c/Users/TestMLEngineer/Desktop/mask_and_crop_align/assets/models/shape_predictor_68_face_landmarks.dat"
model: "assets/models/shape_predictor_68_face_landmarks.dat"